#
# NetSurf build configuration example
#
#
# To configure NetSurf's build options create a Makefile.config file. This is
# an example Makefile.config.
#
# To see the available config options, look at Makefile.defaults


# For example, by default, NetSurf builds with BMP support.  If you
# wish to disable this, then uncomment the following line.

override NETSURF_USE_BMP := NO
override NETSURF_USE_GIF := NO
override NETSURF_USE_MNG := NO
override NETSURF_FB_FONTLIB := freetype

  # freetype compiled in font locations 
override  NETSURF_FB_FONT_SANS_SERIF := /usr/share/fonts/ttf-dejavu/DejaVuSans.ttf
override  NETSURF_FB_FONT_SANS_SERIF_BOLD := /usr/share/fonts/ttf-dejavu/DejaVuSans-Bold.ttf
override  NETSURF_FB_FONT_SANS_SERIF_ITALIC := /usr/share/fonts/ttf-dejavu/DejaVuSans-Oblique.ttf
override  NETSURF_FB_FONT_SANS_SERIF_ITALIC_BOLD := /usr/share/fonts/ttf-dejavu/DejaVuSans-BoldOblique.ttf
override  NETSURF_FB_FONT_SERIF := /usr/share/fonts/ttf-dejavu/DejaVuSerif.ttf
override  NETSURF_FB_FONT_SERIF_BOLD := /usr/share/fonts/ttf-dejavu/DejaVuSerif-Bold.ttf
override  NETSURF_FB_FONT_MONOSPACE := /usr/share/fonts/ttf-dejavu/DejaVuSansMono.ttf
override  NETSURF_FB_FONT_MONOSPACE_BOLD := /usr/share/fonts/ttf-dejavu/DejaVuSansMono-Bold.ttf
override  NETSURF_FB_FONT_CURSIVE := /usr/share/fonts/msttcorefonts/Comic_Sans_MS.ttf
override  NETSURF_FB_FONT_FANTASY := /usr/share/fonts/msttcorefonts/Impact.ttf
