#!/bin/sh

# no need in NanoNote
/etc/init.d/atd disable
/etc/init.d/led disable
/etc/init.d/telnet disable

# write default u-boot env to nand
/usr/bin/mtd.nn fw_setenv_default

# generate fontconfig cache
/usr/bin/fc-cache

exit 0
