#!/bin/sh /etc/rc.common

START=01
STOP=01

start() {
	/usr/bin/poke 0x10003024 0
	/usr/sbin/alsactl restore -f /etc/asound.state
	return 0
}

stop() {
	/usr/sbin/alsactl store -f /etc/asound.state
	killall gmenu2x.bin
	return 0
}
